apiVersion: v1
kind: ConfigMap
metadata:
  name: #{configmapName}#
  namespace: #{namespace}#
data:
  application.yaml: |-
    paths:
      cors:
        urls: #{path-cors-urls}#
    log4j:
      level:
        state: #{log4j-level}#
    logging:
      level:
        org:
          springframework:
            web: #{log-spring}#