##Spring Configuration
server:
  port: 8080
  servlet:
    contextPath: "/modulo-solucion-cuentas/token-api"
spring:
  application:
    name: NU0170001_VTDAPI_MDSCToken
    tagList: pmo,captaciones,dev
