package co.com.bancolombia.assignadvisor.util;

public class Properties {
    public static final String CLASSIFICATION = "PROXY_CLASSIFICATION_GESTION_DE_CUENTAS";
    public static final String CONNECTION_TIMEOUT = "PROXY_CONNECTION_TIMEOUT_GESTION_DE_CUENTAS";
    public static final String ENDPOINT_ACCOUNTS_MANAGEMENT = "PROXY_ENDPOINT_GESTION_DE_CUENTAS";
    public static final String NAMESPACE_ACCOUNTS_MANAGEMENT = "PROXY_GESTION_DE_CUENTAS_NAMESPACE";
    public static final String REQUEST_TIMEOUT = "PROXY_REQUEST_TIMEOUT_GESTION_DE_CUENTAS";
    public static final String SYSTEM_ID = "PROXY_SYSTEM_ID_GESTION_DE_CUENTAS";
    public static final String USERNAME = "PROXY_USERNAME_GESTION_DE_CUENTAS";
    public static final String FWK_SHOW_XML_SOAP_BODY = "FWK_SHOW_XML_SOAP_BODY";

    
    public static final String ENDPOINT_ADVISER_MANAGEMENT = "PROXY_ENDPOINT_MANTENIMIENTO_CUENTAS_DEPOSITO";
	public static final String USERNAME_ADVISER = "PROXY_USERNAME_MANTENIMIENTO_CUENTAS_DEPOSITO";
	public static final String CLASSIFICATION_ADVISER = "PROXY_CLASSIFICATION_MANTENIMIENTO_CUENTAS_DEPOSITO";
	public static final String REQUEST_TIMEOUT_ADVISER = "PROXY_REQUEST_TIMEOUT_MANTENIMIENTO_CUENTAS_DEPOSITO";
	public static final String CONNECTION_TIMEOUT_ADVISER = "PROXY_CONNECTION_TIMEOUT_MANTENIMIENTO_CUENTAS_DEPOSITO";


    
    private Properties() {}
}
