##Spring Configuration
server:
  port: 8080
  servlet:
    contextPath: "/modulo-solucion-cuentas/catalogue-api"
spring:
  application:
    name: NU0170001_VTDAPI_MDSCCatalogos
    tagList: pmo,captaciones,dev,error-api