apiVersion: v1
kind: ConfigMap
metadata:
  name: #{configmapName}#
  namespace: #{namespace}#
data:
  application.yaml: |-
    spring:
      redis:
        server:
          address: #{redis-address}#
          port: #{redis-port}#
    log4j:
      level:
        state: #{log4j-level}#
    logging:
      level:
        org:
          springframework:
            web: #{log-spring}#
    amazon:
      dynamodb:
        endpoint: #{amazon-dynamodb-endpoint}#
        region : #{amazon-dynamodb-region}#
    dynamo:
      table:
        name: #{dynamo-table-catalogue}#
    aws:
      accessKeyId: #{aws-accessKeyId}#
      secretKey : #{aws-secretKey}#
      sessionToken : #{aws-sessionToken}#
    cross:
      data:
        atmwithdrawals: #{cross-atmwithdrawals}#
        bankcorreswithdrawals : #{cross-bankcorreswithdrawals}#
    services:
      account:
        offersplans:
          endpoint: #{account-offersplans-endpoint}#
          clientid: #{account-offersplans-clientid}#
          secretid: #{account-offersplans-secretid}#
          pgkey: #{account-offersplans-pgkey}#
          pgsize: #{account-offersplans-pgsize}#
          statusplan: #{account-offersplans-statusplan}#
          accountype: #{account-offersplans-accountype}#
          customtype: #{account-offersplans-customtype}#
          categoryid: #{account-offersplans-categoryid}#
      kinesis:
        firehose:
          lzReportHead: #{aws-LzReportHeadCatalog}#
      debitCards:
        shareCost:
          endpoint: #{debitCards-shareCost-endpoint}#
          clientid: #{debitCards-shareCost-clientid}#
          secretid: #{debitCards-shareCost-secretid}#